[package]
name = "telegram_remote_hopr_chat"
version = "0.1.0"
authors = ["Aleksandr Savelev <savelev.aleksandr.96@yandex.ru>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
tokio = { version = "0.2.22", features = ["full"] }
telegram-bot = "0.7"
serde_json = "1.0.57"
serde = "1.0.116"
